#!/bin/bash

SCRIPT_DIR="$(realpath "$(dirname "$0")")"

function luks-mount() {
  local device="$1"
  local destination="$2"
  local passphrase="$3"

  if [[ -z "$device" || -d "$device" || -z "$destination" || -z "$passphrase" ]]; then
    echo 'Usage: luks-mount <device> <destination> <passphrase>'
    return 1
  fi

  echo "mkdir -p \"$destination\""
  mkdir -p "$destination"

  local mapping_name="$($SCRIPT_DIR/mapping-name "$device")"

  echo "echo -n \"\${passphrase}\" | cryptsetup open -d - \"$device\" \"$mapping_name\""
  echo -n "${passphrase}" \
    | cryptsetup open -d - "$device" "$mapping_name"

  echo "mount \"/dev/mapper/$mapping_name\" \"$destination\""
  mount "/dev/mapper/$mapping_name" "$destination"
}

if [[ ! -z "$@" ]]; then
  luks-mount "$@"
fi
